FROM ruby:3.3.8-slim

ENV BUNDLE_PATH=/usr/local/bundle

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev libyaml-dev curl git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

EXPOSE 3000

ENTRYPOINT ["bin/docker-entrypoint"]
CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
